### ISSUE TITLE
nice works!

### ISSUE THREAD

**Issue by BlueBlueFF** [FuxiaoLiu/MMC#1]
when will dataset open?

**Comment by FuxiaoLiu** [comment]
I will try to release the dataset this week.

**Comment by nemonameless** [comment]
@FuxiaoLiu 
when will dataset open?

**Comment by Hambaobao** [comment]
Where can we find the dataset?

**Comment by FuxiaoLiu** [comment]
I just finished the NAACL deadline. I will release the benchmark this week. Thanks for your waiting.
