### ISSUE TITLE
Request for summarization data for existing dataset

### ISSUE THREAD

**Issue by yuyq96** [FuxiaoLiu/MMC#10]
Thanks for open-sourcing the MMC training data, which is quite helpful for developing document-oriented MLLMs. I notice that the download link for existing datasets is not updated yet and I believe it is better to include them in our training. Do you have a plan for uploading these images recently?

**Comment by yuyq96** [comment]
Are those images already included in the `nonarxiv_images` for instruction?

**Comment by FuxiaoLiu** [comment]
gdown https://drive.google.com/file/d/1e1mx_nb5PWjPkuIsJkY8B4xSET9DOWTa

**Comment by yuyq96** [comment]
Thanks!
