### ISSUE TITLE
Inquiry Regarding Chart-Text Alignment Data and Instructions

### ISSUE THREAD

**Issue by buckerF** [FuxiaoLiu/MMC#12]
Hello,

I hope this message finds you well. I've been actively exploring the MMC project repository and must say it's an invaluable resource.

I have a few queries regarding the Chart-Text Alignment Data:
- Regarding the non-arXiv JSON files, is the "text" section utilized for the textual alignment?
- Regarding the arXiv JSON files, is the "caption" section utilized for the textual alignment?
- Does the "reference_sentence_in_article" field in the arXiv JSON files play a role in the alignment process?

Your guidance on the construction of instructions for generating the Chart-Text Alignment Data would also be immensely helpful. If possible, could you provide some specifics or some prompts to follow?

Thank you sincerely for your time and consideration.

Warm regards,

**Comment by FuxiaoLiu** [comment]
In the non-arxiv file the “text” section is used for alignment. As for the arxiv section, the “caption” section is used for alignment. As for the prompt, you can regard it as the chart summarization task and use ChatGPT to generate different prompt for this task.
