### ISSUE TITLE
Data bug

### ISSUE THREAD

**Issue by bobo0810** [FuxiaoLiu/MMC#15]
@FuxiaoLiu 
https://huggingface.co/datasets/xywang1/MMC

![image](https://github.com/user-attachments/assets/94f043cb-427b-4344-9324-ad0204b54f85)

**Comment by bobo0810** [comment]
Please ask, there are many placeholders in jsonl, hope it can be repaired as soon as possible. Thank you for your work！

**Comment by FuxiaoLiu** [comment]
Thanks for letting us know! I will fix it

**Comment by xyang0** [comment]
We updated the mmc_instruction_non-arxiv_text.jsonl file in Huggingface with 133 of such data containing placeholders removed. The issue was resolved.

Thanks a lot for the feedback!

**Comment by xyang0** [comment]
We updated the mmc_instruction_non-arxiv_text.jsonl file in Huggingface with 133 of such data containing placeholders removed. The issue was resolved.

Thanks a lot for the feedback!

**Comment by FuxiaoLiu** [comment]
It has been solved
