### ISSUE TITLE
question about MMC Dataset

### ISSUE THREAD

**Issue by hkunzhe** [FuxiaoLiu/MMC#19]
As mentioned by #9 , the updated MMC-Benchmark in [huggingface](https://huggingface.co/datasets/xywang1/MMC/viewer/MMC-Benchmark/) still only contains true-or-false questions. Since the original issue was closed, I reopen this one.

**Comment by FuxiaoLiu** [comment]
You can check the data right here [link](https://drive.google.com/drive/folders/1ukfiCjiT2vbc2tlIlEeiG6oL3SNw0ZCG?usp=share_link).

**Comment by hkunzhe** [comment]
> You can check the data right here [link](https://drive.google.com/drive/folders/1ukfiCjiT2vbc2tlIlEeiG6oL3SNw0ZCG?usp=share_link).

@FuxiaoLiu Thanks for your reply! By the way, I found there are some duplicated question in https://huggingface.co/datasets/xywang1/MMC/viewer/MMC-Benchmark/
<img width="1237" alt="image" src="https://github.com/user-attachments/assets/25180298-1352-453f-baf6-2a109467d02b">
Is this normal?

**Comment by FuxiaoLiu** [comment]
> > You can check the data right here [link](https://drive.google.com/drive/folders/1ukfiCjiT2vbc2tlIlEeiG6oL3SNw0ZCG?usp=share_link).
> 
> @FuxiaoLiu Thanks for your reply! By the way, I found there are some duplicated question in https://huggingface.co/datasets/xywang1/MMC/viewer/MMC-Benchmark/ <img alt="image" width="1237" src="https://private-user-images.githubusercontent.com/30763967/362149856-25180298-1352-453f-baf6-2a109467d02b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjE2NDUsIm5iZiI6MTcyNDg2MTM0NSwicGF0aCI6Ii8zMDc2Mzk2Ny8zNjIxNDk4NTYtMjUxODAyOTgtMTM1Mi00NTNmLWJhZjYtMmExMDk0NjdkMDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE2MDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMTQyMmExNWVhZjk0NjIwZDBhNDc1MGUxMGUzNzBiNjUyZjA0MWVhM2U1NjY1Yzg1ODhkNDI1Mzk0OGZhNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRroGcvW2G_qs-MbfN4L3Qp6vFUKE2nOhfVT8ARcmW0"> Is this normal?

You can skip the duplicated question if the image is the same. I use "random select" method to select the topic for the topic classification tasks. Therefore, as for some images, the questions might be the same.
