### ISSUE TITLE
can not download benchmark json file 

### ISSUE THREAD

**Issue by LightDXY** [FuxiaoLiu/MMC#3]
Nice work, thanks for your efforts. 
However, I found viewers can not download the json file. Any idea about it?
![image](https://github.com/FuxiaoLiu/MMC/assets/18134953/d880eced-0b97-47db-a7c0-c32ead071c0e)

**Comment by kenchan0226** [comment]
Same here.

**Comment by FuxiaoLiu** [comment]
benchmark file has been fixed. https://drive.google.com/file/d/1HOVhPuFJ0roaHt-6AFyYX2E5MxKjoFug

**Comment by Hambaobao** [comment]
Hi, I've also encountered the same issue where it says the file is in the owner's trash, and I'm unable to download other files with `gdown` as well.

**Comment by FuxiaoLiu** [comment]
@Hambaobao the new link of the instruction data is right here. 

https://drive.google.com/drive/folders/1B-uFhUOiSA6am-07r-iS81GAjDmoHXZA?usp=share_link
https://drive.google.com/drive/folders/1LyR_uZ3djITEParCTOrTB9dwjxeZDga1?usp=share_link

If it still doesn't work, please let me know by email. thx!
