### ISSUE TITLE
an empty link of MMC-Benchmark Questions and Answers

### ISSUE THREAD

**Issue by nemonameless** [FuxiaoLiu/MMC#4]
```
MMC-Benchmark
Questions and Answers
gdown https://drive.google.com/file/d/1iojBp5uzTAjZBtGU0cmXawzzWrnzrc1L
```

It is an empty link. please fix it thx

**Comment by FuxiaoLiu** [comment]
Thanks for your reminding, I will fix it asap.

**Comment by zengxingchen** [comment]
the same

**Comment by FuxiaoLiu** [comment]
The new link of the instruction data is right here.
https://drive.google.com/drive/folders/1B-uFhUOiSA6am-07r-iS81GAjDmoHXZA?usp=share_link
https://drive.google.com/drive/folders/1LyR_uZ3djITEParCTOrTB9dwjxeZDga1?usp=share_link

Benchmark file has been fixed.
gdown https://drive.google.com/file/d/1HOVhPuFJ0roaHt-6AFyYX2E5MxKjoFug

If it still doesn't work, please let me know by email. thx!
