### ISSUE TITLE
Some of files cannot be reached

### ISSUE THREAD

**Issue by Moonteresa** [FuxiaoLiu/MMC#5]
These files cannot reach , they report "Sorry, you can't view or download this file at this time."
#Part 1
#Images
gdown https://drive.google.com/file/d/1Y17wNYdBlPxhB5KKiux2BD8C2FlA5MC9
#Text
gdown https://drive.google.com/file/d/1tUtntLRgsBJ9v5NcdTMvVI32ruLHAyFe

**Comment by FuxiaoLiu** [comment]
The new link of the instruction data is right here.

https://drive.google.com/drive/folders/1B-uFhUOiSA6am-07r-iS81GAjDmoHXZA?usp=share_link
https://drive.google.com/drive/folders/1LyR_uZ3djITEParCTOrTB9dwjxeZDga1?usp=share_link

If it still doesn't work, please let me know by email. thx!
