### ISSUE TITLE
Chart-Text Alignment Data

### ISSUE THREAD

**Issue by qingyuanxingsi** [FuxiaoLiu/MMC#6]
Great Work! Can you provide **Chart-Text Alignment Data**? Or how to separate this apart from instruction tuning data?

**Comment by FuxiaoLiu** [comment]
Thanks for your interests in our paper! I will share a version which separates Chart-Text Alignment Data from instruction tuning data in the next few days.

**Comment by qingyuanxingsi** [comment]
I have downloaded all the data? Any quick answers for how to split? @FuxiaoLiu

**Comment by qingyuanxingsi** [comment]
> Thanks for your interests in our paper! I will share a version which separates Chart-Text Alignment Data from instruction tuning data in the next few days.

@FuxiaoLiu Any updates?

**Comment by FuxiaoLiu** [comment]
Thanks for your interests in our paper! Our arXiv chart-text alignment data is here:

#Images
gdown https://drive.google.com/file/d/1pDGOkE8AfVTCdy9-5yTltvGlYzgw0wyk
#Text
gdown https://drive.google.com/file/d/1l7Ft4xIl9fvSuxNQ-QPo0hLP7jNx6Mnt

As for the datasets from existing dataset, we select the data with the chart summarization task from Source: Statist, PlotQA, VisText, ChartInfo, Unichart.

**Comment by FuxiaoLiu** [comment]
Please use the new link to download the images: gdown https://drive.google.com/file/d/1pDGOkE8AfVTCdy9-5yTltvGlYzgw0wyk
