### ISSUE TITLE
Request for Chart-Text Alignment Data Download Link

### ISSUE THREAD

**Issue by buckerF** [FuxiaoLiu/MMC#7]
Hello,

I have been exploring the MMC project repository and find it immensely valuable. I am particularly interested in accessing the Chart-Text Alignment Data to further my research. However, I noticed that the download link provided in the README only includes the Chart Instruction-Tuning Data.

Would it be possible for you to kindly provide the download link for the Chart-Text Alignment Data as well? Access to this dataset would greatly contribute to my work and research efforts.

Thank you very much for your time and consideration.

Best regards,

**Comment by FuxiaoLiu** [comment]
Thanks for your interests in our paper! Our arXiv chart-text alignment data is here:

#Images
gdown https://drive.google.com/file/d/1pDGOkE8AfVTCdy9-5yTltvGlYzgw0wyk
#Text
gdown https://drive.google.com/file/d/1l7Ft4xIl9fvSuxNQ-QPo0hLP7jNx6Mnt

As for the datasets from existing dataset, we select the data with the chart summarization task from Source: Statist, PlotQA, VisText, ChartInfo, Unichart.
