### ISSUE TITLE
Incomplete Arxiv Image Dataset

### ISSUE THREAD

**Issue by buckerF** [FuxiaoLiu/MMC#8]
Hello,

I have downloaded 202k Arxiv images, but it seems incomplete. The JSON data for Scientific (Arxiv) Chart-Caption comprises a total of 250,000 entries. Yet, I found that 79,040 entries reference images that are missing from the dataset provided in [this Google Drive link](https://drive.google.com/file/d/1QKQOMIH9Wd3EQEYr3IV2u9qQXmSZy49G).

Could you kindly provide the missing images or offer insight into why they are not included in the provided dataset?

Thank you for your attention to this matter.

Best regards,

**Comment by FuxiaoLiu** [comment]
Thanks for your question! let me double-check and re-upload the images

**Comment by FuxiaoLiu** [comment]
Please use the new link to download images: gdown https://drive.google.com/file/d/1pDGOkE8AfVTCdy9-5yTltvGlYzgw0wyk

**Comment by buckerF** [comment]
@FuxiaoLiu Thanks!
