### ISSUE TITLE
question about MMC-Benchmark

### ISSUE THREAD

**Issue by beichenzbc** [FuxiaoLiu/MMC#9]
MMC-Benchmark should contain multiple tasks like Multiple-choice questions and Free-form questions according to the paper. However, the data.json downloaded from this link [https://drive.google.com/file/d/1HOVhPuFJ0roaHt-6AFyYX2E5MxKjoFug](https://drive.google.com/file/d/1HOVhPuFJ0roaHt-6AFyYX2E5MxKjoFug) seems to only contain true-or-false questions.

**Comment by FuxiaoLiu** [comment]
Thanks for letting me know! The link is mismatch. I will update the link and let you know.

**Comment by Mohamed-Dhouib** [comment]
Hello @FuxiaoLiu, do you have any idea on when will you be able to fix this ?
